// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace com.Pingvin
{
public static class RoadOfWar
{
        public const string achievement_presistant = "CgkI2Lz88usREAIQBA"; // <GPGSID>
        public const string achievement_mercenary = "CgkI2Lz88usREAIQAw"; // <GPGSID>
        public const string achievement_traveller = "CgkI2Lz88usREAIQAQ"; // <GPGSID>
        public const string achievement_mechanic = "CgkI2Lz88usREAIQBQ"; // <GPGSID>
        public const string achievement_killer = "CgkI2Lz88usREAIQAg"; // <GPGSID>
        public const string leaderboard_top_raiders = "CgkI2Lz88usREAIQBg"; // <GPGSID>

}
}
